<?php
declare(strict_types=1);
const APP_NAME='CM Comercial'; const DB_PATH=__DIR__.'/data/cm_comercial.sqlite'; const BASE_URL=''; const SESSION_TIMEOUT=7200;
$APP_ENV=getenv('APP_ENV')?:'production'; $APP_DEBUG=($APP_ENV!=='production');
if(session_status()!==PHP_SESSION_ACTIVE){$secure=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>$secure,'httponly'=>true,'samesite'=>'Lax']);session_start();}
function security_headers():void{if(headers_sent())return;header('X-Content-Type-Options: nosniff');header('X-Frame-Options: SAMEORIGIN');header('Referrer-Policy: strict-origin-when-cross-origin');header('Permissions-Policy: camera=(), microphone=(), geolocation=()');header('Cross-Origin-Opener-Policy: same-origin');if(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off')header('Strict-Transport-Security: max-age=31536000; includeSubDomains');} security_headers(); if(!$APP_DEBUG){ini_set('display_errors','0');ini_set('log_errors','1');}
function db():PDO{static $pdo=null;if($pdo instanceof PDO)return $pdo;$dir=dirname(DB_PATH);if(!is_dir($dir))mkdir($dir,0775,true);$pdo=new PDO('sqlite:'.DB_PATH);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$pdo->exec('PRAGMA foreign_keys = ON');return $pdo;}
function e(?string $v):string{return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');} function money(float|int $v):string{return 'R$ '.number_format((float)$v,2,',','.');} function is_logged_in():bool{return isset($_SESSION['user']);} function user():?array{return $_SESSION['user']??null;} function is_admin():bool{return is_logged_in()&&(user()['role']??'')==='admin';} function require_login():void{if(!is_logged_in())redirect('login.php');} function require_admin():void{if(!is_admin()){http_response_code(403);include __DIR__.'/403.php';exit;}} function redirect(string $p):never{header('Location: '.$p);exit;}
function csrf_token():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return $_SESSION['csrf'];} function verify_csrf():void{if(!hash_equals($_SESSION['csrf']??'',$_POST['csrf']??'')){http_response_code(419);exit('Token de segurança inválido.');}}
function shipping_methods():array{return db()->query("SELECT * FROM shipping_methods WHERE active=1 ORDER BY id")->fetchAll();}
function calculate_shipping(string $method,string $zip,string $state,float $subtotal):array{if($method==='pickup')return ['fee'=>0.0,'label'=>'Retirar na loja','eta'=>0];$zip=preg_replace('/\D+/','',$zip)??'';$state=strtoupper(trim($state));$rules=db()->query("SELECT * FROM shipping_rules WHERE active=1 AND method_code='delivery' ORDER BY priority DESC, LENGTH(zip_prefix) DESC, id DESC")->fetchAll();foreach($rules as $r){$zm=$r['zip_prefix']===''||str_starts_with($zip,(string)$r['zip_prefix']);$sm=$r['state']===''||strtoupper((string)$r['state'])===$state;if($zm&&$sm){$fee=(float)$r['fee'];if((float)$r['free_above']>0&&$subtotal>=(float)$r['free_above'])$fee=0;return ['fee'=>$fee,'label'=>'Entrega em '.$state,'eta'=>(int)$r['eta_days']];}}return ['fee'=>$subtotal>=999?0.0:29.90,'label'=>'Entrega','eta'=>5];}
function slugify(string $v):string{$v=iconv('UTF-8','ASCII//TRANSLIT//IGNORE',trim($v))?:$v;$v=strtolower($v);$v=preg_replace('/[^a-z0-9]+/','-',$v)??'';return trim($v,'-')?:'produto';} function product_image(array $p):string{return trim((string)($p['image']??''))?:'assets/product-placeholder.svg';}
