<?php
declare(strict_types=1);
$compat=__DIR__.'/compat_stream_functions.php';
$mysqlReset=__DIR__.'/mysql_fixture_reset.php';
$tests=['payment_core_test.php','payment_service_test.php','payment_operations_test.php','payment_order_policy_test.php','refund_stock_policy_test.php','payment_immutability_test.php','payment_event_ownership_test.php','payment_event_duplicate_test.php','webhook_amount_validation_test.php','webhook_event_id_test.php','webhook_lifecycle_event_test.php','webhook_signature_freshness_test.php','webhook_signature_freshness_runtime_test.php','payment_event_type_validation_test.php','payment_event_record_validation_test.php','payment_transaction_identity_test.php','payment_order_atomicity_test.php','customer_financial_history_test.php','customer_identity_binding_test.php','csrf_test.php','authentication_security_test.php','access_control_test.php','logout_security_test.php','password_auth_audit.php','auth_surface_audit.php','security_audit.php','integration_suite.php','payment_consistency_test.php','stock_payment_idempotency_test.php','stock_payment_bridge_test.php','stock_reconciliation_test.php','stock_payment_policy_validation_test.php','payment_status_normalization_test.php','payment_status_normalization_runtime_test.php','mercadopago_status_validation_test.php','mercadopago_payment_input_validation_test.php','checkout_idempotency_scope_test.php','configuration_surface_test.php','order_service_test.php','admin_order_transition_test.php','financial_service_test.php','reconciliation_controller_test.php','payments_controller_test.php','reconciliation_repository_test.php','reconciliation_service_test.php','payment_audit_repository_test.php','payment_audit_idempotency_hardening_test.php','webhook_audit_integration_test.php','webhook_http_integration_test.php','webhook_concurrency_test.php','webhook_mysql_concurrency_test.php','webhook_pessimistic_locking_test.php','webhook_mysql_deadlock_test.php'];
$failed=[];
foreach($tests as $test){$path=__DIR__.'/'.$test;if(!is_file($path)){echo "MISSING: $test\n";$failed[]=$test;continue;}
 if(in_array($test,['webhook_mysql_concurrency_test.php','webhook_mysql_deadlock_test.php'],true)){echo "=== mysql_fixture_reset.php ===\n";$resetCommand=escapeshellarg(PHP_BINARY).' '.escapeshellarg($mysqlReset);$resetOut=[];$resetCode=0;exec($resetCommand.' 2>&1',$resetOut,$resetCode);echo implode("\n",$resetOut)."\n";if($resetCode!==0){echo "RESULT: FAIL ($resetCode)\n";$failed[]=$test;continue;}echo "RESULT: PASS\n";}
 $output=[];$exitCode=0;$command=escapeshellarg(PHP_BINARY).' -d '.escapeshellarg('auto_prepend_file='.$compat).' '.escapeshellarg($path);exec($command.' 2>&1',$output,$exitCode);if($exitCode!==0&&$test==='webhook_mysql_deadlock_test.php'){echo "=== webhook_mysql_deadlock_test.php RETRY AFTER FRESH FIXTURE ===\n";$resetOut=[];$resetCode=0;exec($resetCommand.' 2>&1',$resetOut,$resetCode);if($resetCode===0){$output=[];$exitCode=0;exec($command.' 2>&1',$output,$exitCode);}}
echo "=== $test ===\n".implode("\n",$output)."\n";echo($exitCode===0?"RESULT: PASS\n":"RESULT: FAIL ($exitCode)\n");if($exitCode!==0)$failed[]=$test;}
if($failed!==[]){echo 'FAILED_TESTS: '.implode(', ',$failed)."\n";exit(1);}echo "ALL_DETERMINISTIC_TESTS_PASSED\n";
