<?php
declare(strict_types=1);
require_once __DIR__.'/../vendor/autoload.php';
final class WebhookConcurrencyE2EFailure extends RuntimeException {}
function raceE2EAssert(bool $ok,string $message):void{if(!$ok)throw new WebhookConcurrencyE2EFailure($message);}
function raceE2EDb(string $path):PDO{$pdo=new PDO('sqlite:'.$path,null,null,[PDO::ATTR_TIMEOUT=>10]);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);$pdo->exec('PRAGMA busy_timeout=10000');$pdo->exec('PRAGMA journal_mode=WAL');return $pdo;}
function raceE2EFixture(string $path):void{$pdo=raceE2EDb($path);$pdo->exec("CREATE TABLE users(id INTEGER PRIMARY KEY,name TEXT NOT NULL,email TEXT NOT NULL);CREATE TABLE orders(id INTEGER PRIMARY KEY,customer_id INTEGER,status TEXT NOT NULL,payment_status TEXT NOT NULL,total_amount NUMERIC NOT NULL,currency TEXT NOT NULL,shipping_amount NUMERIC NOT NULL DEFAULT 0,idempotency_key TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE products(id INTEGER PRIMARY KEY,sku TEXT,name TEXT,price NUMERIC NOT NULL,stock_quantity INTEGER NOT NULL,active INTEGER NOT NULL);CREATE TABLE order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,product_id INTEGER NOT NULL,sku TEXT,product_name TEXT,unit_price NUMERIC NOT NULL,quantity INTEGER NOT NULL);CREATE TABLE payment_transactions(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL,provider TEXT NOT NULL,provider_payment_id TEXT,external_reference TEXT NOT NULL,idempotency_key TEXT NOT NULL,status TEXT NOT NULL,amount NUMERIC NOT NULL,currency TEXT NOT NULL,pix_qr_code TEXT,pix_qr_code_base64 TEXT,pix_expires_at TEXT,gateway_payload TEXT,webhook_event_id TEXT,last_webhook_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE payment_audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,payment_transaction_id INTEGER NOT NULL,event_type TEXT NOT NULL,old_status TEXT,new_status TEXT,actor TEXT NOT NULL,idempotency_key TEXT UNIQUE,payload TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE order_status_history(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,from_status TEXT NOT NULL,to_status TEXT NOT NULL,actor_user_id INTEGER,note TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,type TEXT NOT NULL,qty INTEGER NOT NULL,reason TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);");$pdo->exec("INSERT INTO users VALUES(1,'Race Customer','race@example.test');INSERT INTO orders VALUES(10,1,'pending','pending',100,'BRL',0,'checkout-10','2026-09-01 10:00:00','2026-09-01 10:00:00');INSERT INTO products VALUES(50,'SKU-50','Produto Concorrente',50,4,1);INSERT INTO order_items VALUES(1,10,50,'SKU-50','Produto Concorrente',50,2);INSERT INTO payment_transactions(id,order_id,provider,provider_payment_id,external_reference,idempotency_key,status,amount,currency,created_at,updated_at) VALUES(100,10,'mercadopago',NULL,'10','checkout-10','pending',100,'BRL','2026-09-01 10:01:00','2026-09-01 10:01:00');");}
function raceE2ERouter(string $path,string $db,string $interface,string $handler):void{$r=<<<'PHP'
<?php
declare(strict_types=1);
namespace App\Config {
if(!class_exists(Database::class,false)){final class Database{private static ?self $i=null;private \PDO $pdo;private function __construct(){$this->pdo=new \PDO('sqlite:__DB__',null,null,[\PDO::ATTR_TIMEOUT=>10]);$this->pdo->setAttribute(\PDO::ATTR_ERRMODE,\PDO::ERRMODE_EXCEPTION);$this->pdo->setAttribute(\PDO::ATTR_DEFAULT_FETCH_MODE,\PDO::FETCH_ASSOC);$this->pdo->exec('PRAGMA busy_timeout=10000');$this->pdo->exec('PRAGMA journal_mode=WAL');}public static function getInstance():self{return self::$i??=new self();}public function pdo():\PDO{return $this->pdo;}}}
}
namespace App\Gateways {
if(!class_exists(MercadoPagoGateway::class,false)){require_once '__INTERFACE__';final class MercadoPagoGateway implements PaymentGatewayInterface{public function createPixCharge(int $orderId,float $amount,string $payerEmail,string $payerName,string $idempotencyKey):array{throw new \LogicException('race E2E must not create charges');}public function getPayment(string $paymentId):array{return['provider_payment_id'=>$paymentId,'status'=>'paid','transaction_id'=>$paymentId,'raw'=>['external_reference'=>'10','transaction_amount'=>100.00,'access_token'=>'RACE-TOKEN','webhook_secret'=>'RACE-SECRET','authorization'=>'Bearer RACE-AUTH']];}}}
}
namespace {require '__HANDLER__';return true;}
PHP;$r=str_replace(['__DB__','__INTERFACE__','__HANDLER__'],[addslashes($db),addslashes($interface),addslashes($handler)],$r);file_put_contents($path,$r);}
function raceE2EStart(string $root,string $router,string $db,int $port):array{$log=sys_get_temp_dir().'/race-e2e-'.getmypid().'.log';$env=getenv();if(!is_array($env))$env=[];$env['CM_E2E_DB']=$db;$env['MP_WEBHOOK_SECRET']='race-webhook-secret';$env['MP_WEBHOOK_MAX_SKEW']='300';if(PHP_OS_FAMILY!=='Windows')$env['PHP_CLI_SERVER_WORKERS']='8';$cmd=implode(' ',array_map('escapeshellarg',[PHP_BINARY,'-S','127.0.0.1:'.$port,'-t',$root,$router]));$p=proc_open($cmd,[0=>['pipe','r'],1=>['file',$log,'ab'],2=>['file',$log,'ab']],$pipes,$root,$env);raceE2EAssert(is_resource($p),'race HTTP server failed');fclose($pipes[0]);for($i=0;$i<60;$i++){if(($s=@fsockopen('127.0.0.1',$port,$errno,$error,0.1))!==false){fclose($s);return[$p,$log,'http://127.0.0.1:'.$port.'/webhooks/webhook_handler.php'];}usleep(100000);}proc_terminate($p);throw new RuntimeException('race HTTP server not ready');}
function raceE2EPort():int{$s=stream_socket_server('tcp://127.0.0.1:0',$e,$m);raceE2EAssert($s!==false,'port allocation failed');$n=(string)stream_get_name($s,false);fclose($s);return(int)substr($n,strrpos($n,':')+1);}
$root=dirname(__DIR__);$tmp=sys_get_temp_dir().'/cm-race-e2e-'.getmypid().'-'.bin2hex(random_bytes(4));raceE2EAssert(mkdir($tmp,0700,true),'temp directory failed');$db=$tmp.'/race.sqlite';$router=$tmp.'/router.php';$server=null;
try{raceE2EFixture($db);raceE2ERouter($router,$db,$root.'/src/Gateways/PaymentGatewayInterface.php',$root.'/webhooks/webhook_handler.php');[$server,$log,$url]=raceE2EStart($root,$router,$db,raceE2EPort());$payload=['id'=>910001,'type'=>'payment','action'=>'payment.updated','live_mode'=>false,'data'=>['id'=>'777001']];$body=json_encode($payload,JSON_THROW_ON_ERROR);$ts=time();$manifest='id:910001;request-id:race-same;ts:'.$ts.';';$headers=['Content-Type: application/json','x-request-id: race-same','x-signature: ts='.$ts.',v1='.hash_hmac('sha256',$manifest,'race-webhook-secret')];$multi=curl_multi_init();$hs=[];for($i=0;$i<16;$i++){$h=curl_init($url);curl_setopt_array($h,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>$headers,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>30]);curl_multi_add_handle($multi,$h);$hs[]=$h;}$running=null;do{$m=curl_multi_exec($multi,$running);if($running>0)curl_multi_select($multi,1.0);}while($running>0&&$m===CURLM_OK);$statuses=[];foreach($hs as $h){$statuses[]=(int)curl_getinfo($h,CURLINFO_HTTP_CODE);curl_multi_remove_handle($multi,$h);curl_close($h);}curl_multi_close($multi);raceE2EAssert(count($statuses)===16,'expected 16 concurrent responses');raceE2EAssert(count(array_filter($statuses,static fn(int $s):bool=>$s===200))===16,'all concurrent identical requests must return HTTP 200: '.implode(',',$statuses).' log='.(is_file($log)?file_get_contents($log):''));$pdo=raceE2EDb($db);raceE2EAssert((int)$pdo->query('SELECT COUNT(*) FROM payment_audit_log')->fetchColumn()===1,'exactly one audit record expected');raceE2EAssert((int)$pdo->query('SELECT COUNT(*) FROM order_status_history')->fetchColumn()===1,'exactly one order history expected');echo "PASS: webhook_concurrency_test\n";}finally{if(is_resource($server))proc_terminate($server);foreach(glob($tmp.'/*')?:[] as $f)@unlink($f);@rmdir($tmp);}
