<?php
declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

use App\Repositories\PaymentAuditRepository;
use App\Repositories\PaymentTransactionRepository;
use App\Security\WebhookValidator;

final class WebhookAuditIntegrationFailure extends RuntimeException {}
function waAssert(bool $ok,string $message):void{if(!$ok)throw new WebhookAuditIntegrationFailure($message);}
function waSame(mixed $expected,mixed $actual,string $message):void{if($expected!==$actual)throw new WebhookAuditIntegrationFailure($message.' expected='.var_export($expected,true).' actual='.var_export($actual,true));}
function fixture():PDO{
 $pdo=new PDO('sqlite::memory:');$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
 $pdo->exec("CREATE TABLE orders(id INTEGER PRIMARY KEY,customer_id INTEGER,status TEXT,payment_status TEXT,total_amount NUMERIC,currency TEXT DEFAULT 'BRL',created_at TEXT,updated_at TEXT);CREATE TABLE products(id INTEGER PRIMARY KEY,stock_quantity INTEGER NOT NULL);CREATE TABLE order_items(id INTEGER PRIMARY KEY,order_id INTEGER,product_id INTEGER,quantity INTEGER);CREATE TABLE payment_transactions(id INTEGER PRIMARY KEY,order_id INTEGER,provider TEXT,provider_payment_id TEXT,external_reference TEXT,idempotency_key TEXT,status TEXT,amount NUMERIC,currency TEXT,created_at TEXT,updated_at TEXT);CREATE TABLE order_status_history(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER,from_status TEXT,to_status TEXT,actor_user_id INTEGER NULL,note TEXT);CREATE TABLE payment_audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,payment_transaction_id INTEGER,event_type TEXT,old_status TEXT,new_status TEXT,actor TEXT,idempotency_key TEXT UNIQUE,payload TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);");
 $pdo->exec("INSERT INTO orders VALUES(10,1,'pending','pending',100,'BRL','2026-08-31 10:00:00','2026-08-31 10:00:00');INSERT INTO products VALUES(50,1);INSERT INTO order_items VALUES(1,10,50,1);INSERT INTO payment_transactions VALUES(100,10,'mercadopago',NULL,'10','checkout-10','pending',100,'BRL','2026-08-31 10:01:00','2026-08-31 10:01:00');");return $pdo;
}
function signed(array $payload,string $secret,int $ts,string $requestId='fixture-request'):array{$manifest='id:'.$payload['id'].';request-id:'.$requestId.';ts:'.$ts.';';return ['x-signature'=>'ts='.$ts.',v1='.hash_hmac('sha256',$manifest,$secret),'x-request-id'=>$requestId];}
function process(PDO $pdo,array $payload,array $gateway,array $headers):array{
 $validator=new WebhookValidator('fixture-secret',300);waAssert($validator->validate(json_encode($payload,JSON_THROW_ON_ERROR),$headers),'signature must validate');$audit=new PaymentAuditRepository($pdo);$payments=new PaymentTransactionRepository($pdo);$key='mp:webhook:'.$payload['id'];
 return $audit->transaction(static function()use($audit,$payments,$key,$gateway,$payload):array{if($audit->isEventProcessed($key))return['duplicate'=>true];$payment=$payments->findByExternalReference('10',true);waAssert($payment!==null,'payment missing');$auditId=$audit->logEvent(['payment_transaction_id'=>100,'event_type'=>'webhook.payment_updated','old_status'=>$payment['status'],'new_status'=>$gateway['status'],'actor'=>'webhook:mercadopago','idempotency_key'=>$key,'payload'=>['notification_id'=>(string)$payload['id'],'action'=>$payload['action'],'type'=>$payload['type'],'data_id'=>(string)$payload['data']['id']]]);$transition=$payments->applyWebhookTransition(100,(string)$gateway['provider_payment_id'],$gateway['status']);return['duplicate'=>false,'audit_id'=>$auditId,'transition'=>$transition];});
}
$payload=['id'=>900001,'type'=>'payment','action'=>'payment.updated','data'=>['id'=>'777001'],'live_mode'=>false];$headers=signed($payload,'fixture-secret',time());$pdo=fixture();$gateway=['provider_payment_id'=>'777001','status'=>'paid','raw'=>['external_reference'=>'10','transaction_amount'=>100,'access_token'=>'MUST_NOT_BE_PERSISTED','point_of_interaction'=>['transaction_data'=>['qr_code'=>'MUST_NOT_BE_PERSISTED']]]];$r=process($pdo,$payload,$gateway,$headers);waAssert(($r['duplicate']??true)===false,'new event marked duplicate');waSame('paid',$pdo->query('SELECT status FROM payment_transactions WHERE id=100')->fetchColumn(),'payment transition failed');waSame('paid',$pdo->query('SELECT payment_status FROM orders WHERE id=10')->fetchColumn(),'order payment transition failed');waSame(1,(int)$pdo->query('SELECT COUNT(*) FROM payment_audit_log')->fetchColumn(),'audit row missing');$dup=process($pdo,$payload,$gateway,$headers);waAssert(($dup['duplicate']??false)===true,'replay not idempotent');waSame(1,(int)$pdo->query('SELECT COUNT(*) FROM payment_audit_log')->fetchColumn(),'replay duplicated audit');
$rollback=fixture();$audit=new PaymentAuditRepository($rollback);$payments=new PaymentTransactionRepository($rollback);try{$audit->transaction(static function()use($audit,$payments):void{$audit->logEvent(['payment_transaction_id'=>100,'event_type'=>'webhook.payment_updated','old_status'=>'pending','new_status'=>'paid','actor'=>'webhook:mercadopago','idempotency_key'=>'rollback-key','payload'=>[]]);$payments->applyWebhookTransition(100,'777001','paid');throw new RuntimeException('forced rollback');});}catch(RuntimeException $e){waSame('forced rollback',$e->getMessage(),'rollback error mismatch');}waSame('pending',$rollback->query('SELECT status FROM payment_transactions WHERE id=100')->fetchColumn(),'payment rollback failed');waSame('pending',$rollback->query('SELECT payment_status FROM orders WHERE id=10')->fetchColumn(),'order rollback failed');waSame(0,(int)$rollback->query('SELECT COUNT(*) FROM order_status_history')->fetchColumn(),'history rollback failed');waSame(1,(int)$rollback->query('SELECT stock_quantity FROM products WHERE id=50')->fetchColumn(),'stock rollback failed');waSame(0,(int)$rollback->query('SELECT COUNT(*) FROM payment_audit_log')->fetchColumn(),'audit rollback failed');$json=(string)$pdo->query('SELECT payload FROM payment_audit_log')->fetchColumn();waAssert(!str_contains($json,'MUST_NOT_BE_PERSISTED'),'sensitive gateway data persisted');echo "PASS: webhook_audit_integration_test\n";
