<?php
declare(strict_types=1);
require_once __DIR__.'/../vendor/autoload.php';
final class WebhookHttpE2EFailure extends RuntimeException {}
function e2eAssert(bool $ok,string $message):void{if(!$ok)throw new WebhookHttpE2EFailure($message);}
function e2eSame(mixed $expected,mixed $actual,string $message):void{if($expected!==$actual)throw new WebhookHttpE2EFailure($message.' expected='.var_export($expected,true).' actual='.var_export($actual,true));}
function e2eDb(string $path):PDO{$pdo=new PDO('sqlite:'.$path);$pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);$pdo->setAttribute(PDO::ATTR_DEFAULT_FETCH_MODE,PDO::FETCH_ASSOC);return $pdo;}
function e2eFixture(string $path):void{$pdo=e2eDb($path);$pdo->exec("CREATE TABLE orders(id INTEGER PRIMARY KEY,customer_id INTEGER,status TEXT NOT NULL,payment_status TEXT NOT NULL,total_amount NUMERIC NOT NULL,currency TEXT NOT NULL,shipping_amount NUMERIC NOT NULL DEFAULT 0,idempotency_key TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE products(id INTEGER PRIMARY KEY,sku TEXT,name TEXT,price NUMERIC NOT NULL,stock_quantity INTEGER NOT NULL,active INTEGER NOT NULL);CREATE TABLE order_items(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,product_id INTEGER NOT NULL,sku TEXT,product_name TEXT,unit_price NUMERIC NOT NULL,quantity INTEGER NOT NULL);CREATE TABLE payment_transactions(id INTEGER PRIMARY KEY,order_id INTEGER NOT NULL,provider TEXT NOT NULL,provider_payment_id TEXT NULL,external_reference TEXT NOT NULL,idempotency_key TEXT NOT NULL,status TEXT NOT NULL,amount NUMERIC NOT NULL,currency TEXT NOT NULL,pix_qr_code TEXT NULL,pix_qr_code_base64 TEXT NULL,pix_expires_at TEXT NULL,gateway_payload TEXT NULL,created_at TEXT NOT NULL,updated_at TEXT NOT NULL);CREATE TABLE payment_audit_log(id INTEGER PRIMARY KEY AUTOINCREMENT,payment_transaction_id INTEGER NOT NULL,event_type TEXT NOT NULL,old_status TEXT NULL,new_status TEXT NULL,actor TEXT NOT NULL,idempotency_key TEXT UNIQUE,payload TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE order_status_history(id INTEGER PRIMARY KEY AUTOINCREMENT,order_id INTEGER NOT NULL,from_status TEXT NOT NULL,to_status TEXT NOT NULL,actor_user_id INTEGER NULL,note TEXT NOT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);CREATE TABLE stock_movements(id INTEGER PRIMARY KEY AUTOINCREMENT,product_id INTEGER NOT NULL,type TEXT NOT NULL,qty INTEGER NOT NULL,reason TEXT NULL,created_at TEXT DEFAULT CURRENT_TIMESTAMP);");$pdo->exec("INSERT INTO orders VALUES(10,1,'pending','pending',100,'BRL',0,'checkout-10','2026-08-31 10:00:00','2026-08-31 10:00:00');INSERT INTO products VALUES(50,'SKU-50','Produto E2E',50,4,1);INSERT INTO order_items VALUES(1,10,50,'SKU-50','Produto E2E',50,2);INSERT INTO payment_transactions(id,order_id,provider,provider_payment_id,external_reference,idempotency_key,status,amount,currency,pix_qr_code,pix_qr_code_base64,pix_expires_at,gateway_payload,created_at,updated_at) VALUES(100,10,'mercadopago',NULL,'10','checkout-10','pending',100,'BRL',NULL,NULL,NULL,NULL,'2026-08-31 10:01:00','2026-08-31 10:01:00');");}
function e2eRouter(string $path,string $dbPath,string $tracePath,string $interfacePath,string $handlerPath):void{$router=<<<'PHP'
<?php
declare(strict_types=1);
namespace App\Config;
if(!class_exists(Database::class,false)){final class Database{private static ?self $instance=null;private \PDO $pdo;private function __construct(){$this->pdo=new \PDO('sqlite:__DB__');$this->pdo->setAttribute(\PDO::ATTR_ERRMODE,\PDO::ERRMODE_EXCEPTION);$this->pdo->setAttribute(\PDO::ATTR_DEFAULT_FETCH_MODE,\PDO::FETCH_ASSOC);}public static function getInstance():self{return self::$instance??=new self();}public function pdo():\PDO{return $this->pdo;}public function transaction(callable $callback):mixed{$this->pdo->beginTransaction();try{$r=$callback($this->pdo);$this->pdo->commit();return $r;}catch(\Throwable $e){if($this->pdo->inTransaction())$this->pdo->rollBack();throw $e;}}}}
namespace App\Gateways;
if(!class_exists(MercadoPagoGateway::class,false)){require_once '__INTERFACE__';final class MercadoPagoGateway implements PaymentGatewayInterface{public function createPixCharge(int $orderId,float $amount,string $payerEmail,string $payerName,string $idempotencyKey):array{throw new \LogicException('E2E gateway must not create charges.');}public function getPayment(string $paymentId):array{return['provider_payment_id'=>$paymentId,'status'=>'paid','transaction_id'=>$paymentId,'pix_qr_code'=>'RAW-PIX-QR-MUST-NOT-BE-PERSISTED','pix_qr_code_base64'=>'RAW-PIX-BASE64-MUST-NOT-BE-PERSISTED','pix_expires_at'=>'2026-09-01T04:00:00+00:00','raw'=>['id'=>(int)$paymentId,'status'=>'approved','external_reference'=>'10','transaction_amount'=>100.00,'access_token'=>'E2E-ACCESS-TOKEN-MUST-NOT-BE-PERSISTED','webhook_secret'=>'E2E-WEBHOOK-SECRET-MUST-NOT-BE-PERSISTED','authorization'=>'Bearer E2E-AUTH-MUST-NOT-BE-PERSISTED','point_of_interaction'=>['transaction_data'=>['qr_code'=>'RAW-PIX-QR-MUST-NOT-BE-PERSISTED']]]];}}}
namespace {file_put_contents('__TRACE__',json_encode(['method'=>$_SERVER['REQUEST_METHOD']??'','request_id'=>$_SERVER['HTTP_X_REQUEST_ID']??'','signature_present'=>isset($_SERVER['HTTP_X_SIGNATURE'])],JSON_UNESCAPED_SLASHES).PHP_EOL,FILE_APPEND|LOCK_EX);require '__HANDLER__';return true;}
PHP;$router=str_replace(['__DB__','__INTERFACE__','__TRACE__','__HANDLER__'],[addslashes($dbPath),addslashes($interfacePath),addslashes($tracePath),addslashes($handlerPath)],$router);file_put_contents($path,$router);}
function e2ePort():int{$s=stream_socket_server('tcp://127.0.0.1:0',$errno,$error);e2eAssert($s!==false,'port allocation failed');$name=(string)stream_get_name($s,false);fclose($s);return (int)substr($name,strrpos($name,':')+1);}
function e2eStart(string $repo,string $router,int $port,string $db):array{$log=sys_get_temp_dir().'/cm-e2e-'.getmypid().'.log';$cmd=implode(' ',array_map('escapeshellarg',[PHP_BINARY,'-S','127.0.0.1:'.$port,'-t',$repo,$router]));$env=getenv();if(!is_array($env))$env=[];$env['CM_E2E_DB']=$db;$env['MP_WEBHOOK_SECRET']='e2e-webhook-secret';$env['MP_WEBHOOK_MAX_SKEW']='300';$p=proc_open($cmd,[0=>['pipe','r'],1=>['file',$log,'ab'],2=>['file',$log,'ab']],$pipes,$repo,$env);e2eAssert(is_resource($p),'HTTP server start failed');fclose($pipes[0]);for($i=0;$i<50;$i++){if(($s=@fsockopen('127.0.0.1',$port,$errno,$error,0.1))!==false){fclose($s);return[$p,$log,$port];}usleep(100000);}proc_terminate($p);throw new RuntimeException('HTTP server not ready: '.(is_file($log)?file_get_contents($log):''));}
function e2ePost(string $url,string $body,array $headers):array{$h=curl_init($url);e2eAssert($h!==false,'curl init failed');$lines=[];foreach($headers as $k=>$v)$lines[]=$k.': '.$v;curl_setopt_array($h,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>$lines,CURLOPT_CONNECTTIMEOUT=>3,CURLOPT_TIMEOUT=>10,CURLOPT_FOLLOWLOCATION=>false]);$bodyOut=curl_exec($h);$error=curl_error($h);$status=(int)curl_getinfo($h,CURLINFO_HTTP_CODE);curl_close($h);e2eAssert($bodyOut!==false&&$error==='','HTTP transport failed: '.$error);return[$status,(string)$bodyOut];}
function e2eSigned(array $payload,string $secret,string $requestId,int $timestamp):array{$manifest='id:'.$payload['id'].';request-id:'.$requestId.';ts:'.$timestamp.';';return['Content-Type'=>'application/json','x-request-id'=>$requestId,'x-signature'=>'ts='.$timestamp.',v1='.hash_hmac('sha256',$manifest,$secret)];}
function e2eJson(string $body):array{$v=json_decode($body,true);return is_array($v)?$v:[];}
$root=dirname(__DIR__);$tmp=sys_get_temp_dir().'/cm-http-e2e-'.getmypid().'-'.bin2hex(random_bytes(4));e2eAssert(mkdir($tmp,0700,true),'temp directory failed');$db=$tmp.'/fixture.sqlite';$router=$tmp.'/router.php';$trace=$tmp.'/trace.log';$secret='e2e-webhook-secret';$server=null;
try{e2eFixture($db);e2eRouter($router,$db,$trace,$root.'/src/Gateways/PaymentGatewayInterface.php',$root.'/webhooks/webhook_handler.php');[$server,$log,$port]=e2eStart($root,$router,e2ePort(),$db);$url='http://127.0.0.1:'.$port.'/webhooks/webhook_handler.php';$payload=['id'=>900001,'type'=>'payment','action'=>'payment.updated','live_mode'=>false,'data'=>['id'=>'777001']];$body=json_encode($payload,JSON_THROW_ON_ERROR);
[$status,$response]=e2ePost($url,$body,e2eSigned($payload,$secret,'e2e-request-1',time()));e2eSame(200,$status,'valid webhook must return HTTP 200');e2eSame(true,e2eJson($response)['received']??false,'success response must confirm receipt');$pdo=e2eDb($db);e2eSame('paid',(string)$pdo->query('SELECT status FROM payment_transactions WHERE id=100')->fetchColumn(),'payment status must transition');e2eSame('paid',(string)$pdo->query('SELECT payment_status FROM orders WHERE id=10')->fetchColumn(),'order payment status must transition');e2eSame(4,(int)$pdo->query('SELECT stock_quantity FROM products WHERE id=50')->fetchColumn(),'paid webhook must not change stock');e2eSame(1,(int)$pdo->query('SELECT COUNT(*) FROM payment_audit_log')->fetchColumn(),'success must create one audit');e2eSame(1,(int)$pdo->query('SELECT COUNT(*) FROM order_status_history')->fetchColumn(),'success must create one history');e2eAssert(str_contains((string)file_get_contents($trace),'e2e-request-1'),'request id did not reach entry point');
[$status,$response]=e2ePost($url,$body,e2eSigned($payload,$secret,'e2e-request-1',time()));e2eSame(200,$status,'replay must return HTTP 200');e2eSame(true,e2eJson($response)['idempotent']??false,'replay must be idempotent');e2eSame(1,(int)$pdo->query('SELECT COUNT(*) FROM payment_audit_log')->fetchColumn(),'replay duplicated audit');e2eSame(1,(int)$pdo->query('SELECT COUNT(*) FROM order_status_history')->fetchColumn(),'replay duplicated history');
$invalid=e2eSigned($payload,$secret,'bad-hmac',time());$invalid['x-signature']='ts='.time().',v1='.str_repeat('0',64);[$status]=e2ePost($url,$body,$invalid);e2eSame(401,$status,'invalid HMAC must return 401');[$status]=e2ePost($url,$body,['Content-Type'=>'application/json','x-request-id'=>'missing-signature']);e2eSame(401,$status,'missing signature must return 401');[$status]=e2ePost($url,$body,e2eSigned($payload,$secret,'expired',time()-301));e2eAssert(in_array($status,[401,403],true),'expired signature must return defensive 4xx');$invalidPayload=$payload;$invalidPayload['id']=900002;$invalidPayload['type']='';[$status]=e2ePost($url,json_encode($invalidPayload,JSON_THROW_ON_ERROR),e2eSigned($invalidPayload,$secret,'semantic-invalid',time()));e2eSame(422,$status,'signed semantic error must return 422');
$pdo->exec("UPDATE payment_transactions SET status='pending',provider_payment_id=NULL WHERE id=100");$pdo->exec("UPDATE orders SET status='pending',payment_status='pending' WHERE id=10");$pdo->exec('DELETE FROM payment_audit_log');$pdo->exec('DELETE FROM order_status_history');$pdo->exec("CREATE TRIGGER fail_webhook_transition BEFORE UPDATE OF status ON payment_transactions WHEN NEW.status='paid' BEGIN SELECT RAISE(ABORT,'forced E2E transition failure'); END");$rollback=$payload;$rollback['id']=900004;[$status]=e2ePost($url,json_encode($rollback,JSON_THROW_ON_ERROR),e2eSigned($rollback,$secret,'rollback',time()));e2eSame(500,$status,'forced intermediate failure must return 500');e2eSame('pending',(string)$pdo->query('SELECT status FROM payment_transactions WHERE id=100')->fetchColumn(),'payment did not rollback');e2eSame('pending',(string)$pdo->query('SELECT payment_status FROM orders WHERE id=10')->fetchColumn(),'order did not rollback');e2eSame(0,(int)$pdo->query('SELECT COUNT(*) FROM payment_audit_log')->fetchColumn(),'audit did not rollback');e2eSame(0,(int)$pdo->query('SELECT COUNT(*) FROM order_status_history')->fetchColumn(),'history did not rollback');$pdo->exec('DROP TRIGGER fail_webhook_transition');
$san=$payload;$san['id']=900005;[$status]=e2ePost($url,json_encode($san,JSON_THROW_ON_ERROR),e2eSigned($san,$secret,'sanitization',time()));e2eSame(200,$status,'sanitization webhook must return 200');$audit=json_encode($pdo->query('SELECT payload FROM payment_audit_log')->fetchAll(),JSON_THROW_ON_ERROR);foreach(['E2E-ACCESS-TOKEN-MUST-NOT-BE-PERSISTED','E2E-WEBHOOK-SECRET-MUST-NOT-BE-PERSISTED','Bearer E2E-AUTH-MUST-NOT-BE-PERSISTED','RAW-PIX-QR-MUST-NOT-BE-PERSISTED'] as $secretValue)e2eAssert(!str_contains($audit,$secretValue),'sensitive gateway data persisted');echo "PASS: webhook_http_integration_test\n";
}finally{if(is_resource($server))proc_terminate($server);if(isset($tmp)&&is_dir($tmp)){foreach(glob($tmp.'/*')?:[] as $f)@unlink($f);@rmdir($tmp);}}
