<?php
declare(strict_types=1);

/** MySQL 8 / InnoDB deterministic 1205/1213 integration gate. */
final class WebhookMySqlDeadlockFailure extends RuntimeException {}
function dmAssert(bool $ok,string $message):void{if(!$ok)throw new WebhookMySqlDeadlockFailure($message);}
function dmSame(mixed $expected,mixed $actual,string $message):void{if($expected!==$actual)throw new WebhookMySqlDeadlockFailure($message.' expected='.var_export($expected,true).' actual='.var_export($actual,true));}
function envOk():bool{foreach(['CM_WEBHOOK_URL','CM_WEBHOOK_SECRET','CM_MYSQL_PAYMENT_ID','CM_MYSQL_ORDER_ID','CM_MYSQL_PROVIDER_PAYMENT_ID_PAID'] as $name){if(getenv($name)===false||trim((string)getenv($name))==='')return false;}return getenv('CM_MYSQL_DSN')!==false||(getenv('CM_MYSQL_HOST')!==false&&getenv('CM_MYSQL_DATABASE')!==false&&getenv('CM_MYSQL_USER')!==false);}
function db():PDO{$dsn=trim((string)(getenv('CM_MYSQL_DSN')?:''));if($dsn==='')$dsn=sprintf('mysql:host=%s;port=%d;dbname=%s;charset=utf8mb4',getenv('CM_MYSQL_HOST'),(int)(getenv('CM_MYSQL_PORT')?:3306),getenv('CM_MYSQL_DATABASE'));return new PDO($dsn,(string)getenv('CM_MYSQL_USER'),(string)(getenv('CM_MYSQL_PASSWORD')?:''),[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false,PDO::ATTR_TIMEOUT=>10]);}
function scalar(PDO $pdo,string $sql,array $params=[]):mixed{$s=$pdo->prepare($sql);$s->execute($params);return $s->fetchColumn();}
function row(PDO $pdo,string $sql,array $params=[]):array{$s=$pdo->prepare($sql);$s->execute($params);$r=$s->fetch(PDO::FETCH_ASSOC);return is_array($r)?$r:[];}
function codes(PDOException $e):array{return[(string)$e->getCode(),isset($e->errorInfo[1])?(int)$e->errorInfo[1]:0];}
function orderProductIds(PDO $pdo,int $orderId):array{$s=$pdo->prepare('SELECT product_id FROM order_items WHERE order_id=? ORDER BY product_id');$s->execute([$orderId]);return array_values(array_unique(array_map('intval',array_column($s->fetchAll(),'product_id'))));}
function stockSnapshot(PDO $pdo,int $orderId):array{$ids=orderProductIds($pdo,$orderId);if($ids===[])return['count'=>0,'quantity'=>0];$p=implode(',',array_fill(0,count($ids),'?'));return['count'=>(int)scalar($pdo,'SELECT COUNT(*) FROM stock_movements WHERE product_id IN ('.$p.')',$ids),'quantity'=>(int)scalar($pdo,'SELECT COALESCE(SUM(qty),0) FROM stock_movements WHERE product_id IN ('.$p.')',$ids)];}
function snapshot(PDO $pdo,int $paymentId,int $orderId):array{return['payment'=>row($pdo,'SELECT status,provider_payment_id,amount FROM payment_transactions WHERE id=?',[$paymentId]),'order'=>row($pdo,'SELECT status,payment_status,total_amount FROM orders WHERE id=?',[$orderId]),'history'=>(int)scalar($pdo,'SELECT COUNT(*) FROM order_status_history WHERE order_id=?',[$orderId]),'stock'=>stockSnapshot($pdo,$orderId),'audit'=>(int)scalar($pdo,'SELECT COUNT(*) FROM payment_audit_log WHERE payment_transaction_id=?',[$paymentId])];}
function markerSnapshot(PDO $pdo,string $marker):array{return['payment'=>(int)scalar($pdo,'SELECT COUNT(*) FROM payment_transactions WHERE provider_payment_id=?',[$marker]),'order'=>(int)scalar($pdo,'SELECT COUNT(*) FROM orders WHERE idempotency_key=?',[$marker]),'history'=>(int)scalar($pdo,'SELECT COUNT(*) FROM order_status_history WHERE note=?',[$marker]),'stock'=>(int)scalar($pdo,'SELECT COUNT(*) FROM stock_movements WHERE reason=? AND product_id IN (2,3)',[$marker]),'audit'=>(int)scalar($pdo,'SELECT COUNT(*) FROM payment_audit_log WHERE idempotency_key=?',[$marker])];}
function waitFile(string $file,int $seconds=10):void{$deadline=microtime(true)+$seconds;while(!is_file($file)&&microtime(true)<$deadline)usleep(10000);dmAssert(is_file($file),'worker synchronization timeout: '.$file);}
function webhook(string $url,string $secret,string $notificationId,string $paymentId):array{$requestId='deadlock-'.bin2hex(random_bytes(6));$ts=time();$body=json_encode(['id'=>$notificationId,'type'=>'payment','action'=>'payment.updated','data'=>['id'=>$paymentId],'live_mode'=>false],JSON_THROW_ON_ERROR);$manifest='id:'.$notificationId.';request-id:'.$requestId.';ts:'.$ts.';';$h=curl_init($url);dmAssert($h!==false,'curl_init failed');curl_setopt_array($h,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$body,CURLOPT_HTTPHEADER=>['Content-Type: application/json','Accept: application/json','x-request-id: '.$requestId,'x-signature: ts='.$ts.',v1='.hash_hmac('sha256',$manifest,$secret)],CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_TIMEOUT=>20,CURLOPT_FOLLOWLOCATION=>false]);$out=curl_exec($h);$r=['status'=>(int)curl_getinfo($h,CURLINFO_HTTP_CODE),'body'=>(string)$out,'error'=>curl_error($h)];curl_close($h);return$r;}
function telemetry(PDO $pdo):array{$result=['locks'=>[],'waits'=>[]];try{$result['locks']=$pdo->query('SELECT * FROM performance_schema.data_locks')->fetchAll(PDO::FETCH_ASSOC);if($result['locks']===[])fwrite(STDERR,"WARN: performance_schema.data_locks returned no rows; continuing with real lock/deadlock assertions\n");}catch(Throwable $e){fwrite(STDERR,'WARN: performance_schema.data_locks telemetry unavailable: '.$e->getMessage()."; continuing with real lock/deadlock assertions\n");}try{$result['waits']=$pdo->query('SELECT * FROM performance_schema.data_lock_waits')->fetchAll(PDO::FETCH_ASSOC);if($result['waits']===[])fwrite(STDERR,"WARN: performance_schema.data_lock_waits returned no rows; continuing with real lock/deadlock assertions\n");}catch(Throwable $e){fwrite(STDERR,'WARN: performance_schema.data_lock_waits telemetry unavailable: '.$e->getMessage()."; continuing with real lock/deadlock assertions\n");}return $result;}
function deadlockSection(PDO $pdo):string{$text=(string)$pdo->query('SHOW ENGINE INNODB STATUS')->fetchColumn(2);$start=strpos($text,'LATEST DETECTED DEADLOCK');if($start===false)return '';return substr($text,$start,min(6000,strlen($text)-$start));}
function deadlockMetric(PDO $pdo):int{$s=$pdo->query("SHOW GLOBAL STATUS LIKE 'Innodb_deadlocks'")->fetch(PDO::FETCH_ASSOC);return(int)($s['Value']??0);}
function waitForDeadlockEvidence(PDO $pdo,int $before):array{$metric=$before;$latest='';for($i=0;$i<30;$i++){ $metric=deadlockMetric($pdo);$latest=deadlockSection($pdo);if($metric>$before||$latest!=='')break;if($i<29)usleep(50000);}return['metric'=>$metric,'latest'=>$latest];}

if(!extension_loaded('pdo_mysql')||!extension_loaded('curl')||!function_exists('pcntl_fork')){echo"SKIP: pdo_mysql, curl and pcntl_fork are required\n";exit(0);}if(!envOk()){echo"SKIP: MySQL deadlock integration environment not configured\n";exit(0);}
try{
 $pdo=db();$version=(string)$pdo->query('SELECT VERSION()')->fetchColumn();dmAssert(preg_match('/^8\./',$version)===1,'MySQL 8 required: '.$version);$paymentId=(int)getenv('CM_MYSQL_PAYMENT_ID');$orderId=(int)getenv('CM_MYSQL_ORDER_ID');$pdo->exec("DELETE FROM payment_audit_log WHERE idempotency_key IN ('deadlock-A','deadlock-B')");$pdo->exec("DELETE FROM order_status_history WHERE note IN ('deadlock-A','deadlock-B')");$pdo->exec("DELETE FROM stock_movements WHERE reason IN ('deadlock-A','deadlock-B')");$pdo->exec("UPDATE payment_transactions SET provider_payment_id=NULL WHERE provider_payment_id IN ('deadlock-A','deadlock-B')");$before=snapshot($pdo,$paymentId,$orderId);$deadlocksBefore=deadlockMetric($pdo);unset($pdo);

 $result1205=tempnam(sys_get_temp_dir(),'cm1205-result-');$ready1205=tempnam(sys_get_temp_dir(),'cm1205-ready-');dmAssert($result1205!==false&&$ready1205!==false,'1205 temp files failed');$child=pcntl_fork();dmAssert($child!==-1,'pcntl_fork failed');
 if($child===0){try{waitFile($ready1205);$b=db();$b->exec('SET SESSION innodb_lock_wait_timeout=1');$b->beginTransaction();$b->prepare('SELECT id FROM payment_transactions WHERE id=? FOR UPDATE')->execute([$paymentId]);file_put_contents($result1205,'FAIL:lock_acquired');$b->rollBack();exit(1);}catch(PDOException $e){[$sql,$vendor]=codes($e);$ok=$sql==='HY000'&&$vendor===1205;file_put_contents($result1205,$ok?'PASS':'FAIL:'.$sql.':'.$vendor.':'.$e->getMessage());if(isset($b)&&$b->inTransaction())$b->rollBack();exit($ok?0:1);}catch(Throwable $e){file_put_contents($result1205,'FAIL:'.get_class($e).':'.$e->getMessage());exit(1);}}
 $a=db();$a->exec('SET SESSION innodb_lock_wait_timeout=5');$a->beginTransaction();$a->prepare('SELECT id FROM payment_transactions WHERE id=? FOR UPDATE')->execute([$paymentId]);$lockTelemetry=telemetry($a);echo 'P_S_LOCKS: '.count($lockTelemetry['locks']).PHP_EOL;echo 'P_S_WAITS_BEFORE: '.count($lockTelemetry['waits']).PHP_EOL;file_put_contents($ready1205,'READY');usleep(200000);$waitStatus=0;pcntl_waitpid($child,$waitStatus);$a->rollBack();$waitResult=trim((string)file_get_contents($result1205));dmAssert(pcntl_wexitstatus($waitStatus)===0&&$waitResult==='PASS','1205/HY000 not observed: '.$waitResult);$check=db();dmSame($before,snapshot($check,$paymentId,$orderId),'1205 left residual mutation');unset($check);@unlink($result1205);@unlink($ready1205);

 $ready=tempnam(sys_get_temp_dir(),'cm1213-ready-');$go=tempnam(sys_get_temp_dir(),'cm1213-go-');$result=tempnam(sys_get_temp_dir(),'cm1213-result-');dmAssert($ready!==false&&$go!==false&&$result!==false,'1213 temp files failed');$child=pcntl_fork();dmAssert($child!==-1,'pcntl_fork failed');
 if($child===0){$outcome='';try{$b=db();$b->exec('SET SESSION innodb_lock_wait_timeout=5');$b->beginTransaction();$b->prepare('SELECT id FROM orders WHERE id=? FOR UPDATE')->execute([$orderId]);$b->prepare("UPDATE payment_transactions SET provider_payment_id='deadlock-B' WHERE id=3")->execute([]);$b->prepare("UPDATE orders SET total_amount=301.00 WHERE id=3")->execute([]);$b->prepare("INSERT INTO order_status_history(order_id,from_status,to_status,actor_user_id,note) VALUES(3,'pending','confirmed',NULL,'deadlock-B')")->execute([]);$b->prepare("INSERT INTO stock_movements(product_id,type,qty,reason) VALUES(3,'adjustment',1,'deadlock-B')")->execute([]);$b->prepare("INSERT INTO payment_audit_log(payment_transaction_id,event_type,old_status,new_status,actor,idempotency_key,payload) VALUES(3,'deadlock','pending','authorized','test','deadlock-B','{}')")->execute([]);file_put_contents($ready,'READY');waitFile($go);usleep(200000);try{$b->prepare('SELECT id FROM payment_transactions WHERE id=? FOR UPDATE')->execute([$paymentId]);$b->commit();$outcome='SURVIVOR';}catch(PDOException $e){[$sql,$vendor]=codes($e);if($sql==='40001'&&$vendor===1213){$outcome='VICTIM';}else{$outcome='ERROR:'.$sql.':'.$vendor;}if($b->inTransaction())$b->rollBack();}}catch(Throwable $e){$outcome='ERROR:'.$e->getMessage();if(isset($b)&&$b->inTransaction())$b->rollBack();}finally{file_put_contents($result,$outcome);}exit($outcome==='VICTIM'||$outcome==='SURVIVOR'?0:1);}
 waitFile($ready);$a=db();$a->exec('SET SESSION innodb_lock_wait_timeout=5');$a->beginTransaction();$a->prepare('SELECT id FROM payment_transactions WHERE id=? FOR UPDATE')->execute([$paymentId]);$a->prepare("UPDATE payment_transactions SET provider_payment_id='deadlock-A' WHERE id=2")->execute([]);$a->prepare("UPDATE orders SET total_amount=201.00 WHERE id=2")->execute([]);$a->prepare("INSERT INTO order_status_history(order_id,from_status,to_status,actor_user_id,note) VALUES(2,'pending','confirmed',NULL,'deadlock-A')")->execute([]);$a->prepare("INSERT INTO stock_movements(product_id,type,qty,reason) VALUES(2,'adjustment',1,'deadlock-A')")->execute([]);$a->prepare("INSERT INTO payment_audit_log(payment_transaction_id,event_type,old_status,new_status,actor,idempotency_key,payload) VALUES(2,'deadlock','pending','authorized','test','deadlock-A','{}')")->execute([]);$telemetryBeforeCross=telemetry($a);echo 'P_S_LOCKS_AFTER_OPPOSITE_LOCKS: '.count($telemetryBeforeCross['locks']).PHP_EOL;echo 'P_S_WAITS_AFTER_OPPOSITE_LOCKS: '.count($telemetryBeforeCross['waits']).PHP_EOL;file_put_contents($go,'GO');usleep(100000);
 $parentOutcome='';try{$a->prepare('SELECT id FROM orders WHERE id=? FOR UPDATE')->execute([$orderId]);$a->commit();$parentOutcome='SURVIVOR';}catch(PDOException $e){[$sql,$vendor]=codes($e);if($sql==='40001'&&$vendor===1213){$parentOutcome='VICTIM';}else{$parentOutcome='ERROR:'.$sql.':'.$vendor;}if($a->inTransaction())$a->rollBack();}file_put_contents($result.'.parent',$parentOutcome);
 $waitStatus=0;pcntl_waitpid($child,$waitStatus);$childOutcome=trim((string)file_get_contents($result));dmAssert(in_array($parentOutcome,['VICTIM','SURVIVOR'],true),'parent did not complete as victim/survivor: '.$parentOutcome);dmAssert(in_array($childOutcome,['VICTIM','SURVIVOR'],true),'child did not complete as victim/survivor: '.$childOutcome);dmAssert($parentOutcome!==$childOutcome,'deadlock outcome invalid: both transactions reported '.$parentOutcome);dmAssert(pcntl_wexitstatus($waitStatus)===0,'deadlock child exited with failure: '.$childOutcome);echo 'DEADLOCK_PARENT_OUTCOME: '.$parentOutcome.PHP_EOL;echo 'DEADLOCK_CHILD_OUTCOME: '.$childOutcome.PHP_EOL;
 $pdo=db();$evidence=waitForDeadlockEvidence($pdo,$deadlocksBefore);$deadlocksAfter=$evidence['metric'];$latest=$evidence['latest'];dmAssert($deadlocksAfter>$deadlocksBefore||$latest!=='','no empirical InnoDB deadlock evidence: counter did not increment and LATEST DETECTED DEADLOCK is absent');echo "LATEST DETECTED DEADLOCK\n".$latest."\nEND LATEST DETECTED DEADLOCK\n";echo 'INNODB_DEADLOCKS_BEFORE: '.$deadlocksBefore.PHP_EOL;echo 'INNODB_DEADLOCKS_AFTER: '.$deadlocksAfter.PHP_EOL;
 $aMarker=markerSnapshot($pdo,'deadlock-A');$bMarker=markerSnapshot($pdo,'deadlock-B');$aExpected=$parentOutcome==='VICTIM';$bExpected=$childOutcome==='VICTIM';dmAssert($aExpected===($parentOutcome==='VICTIM'),'internal parent outcome mismatch');dmAssert($bExpected===($childOutcome==='VICTIM'),'internal child outcome mismatch');if($aExpected){dmAssert(array_sum($aMarker)===0,'deadlock-A victim markers remained; atomic rollback failed');dmAssert(array_sum($bMarker)>0,'deadlock-B survivor markers missing; deadlock survivor did not commit');}else{dmAssert(array_sum($bMarker)===0,'deadlock-B victim markers remained; atomic rollback failed');dmAssert(array_sum($aMarker)>0,'deadlock-A survivor markers missing; deadlock survivor did not commit');}echo 'ROLLBACK_VICTIM_MARKERS: '.json_encode($aExpected?$aMarker:$bMarker,JSON_THROW_ON_ERROR).PHP_EOL;echo 'SURVIVOR_MARKERS: '.json_encode($aExpected?$bMarker:$aMarker,JSON_THROW_ON_ERROR).PHP_EOL;@unlink($ready);@unlink($go);@unlink($result);@unlink($result.'.parent');

 $a=db();$a->beginTransaction();$a->prepare('SELECT id FROM payment_transactions WHERE id=? FOR UPDATE')->execute([$paymentId]);$timeoutControl=db();$timeoutControl->exec('SET GLOBAL innodb_lock_wait_timeout=1');$http=null;try{$http=webhook((string)getenv('CM_WEBHOOK_URL'),(string)getenv('CM_WEBHOOK_SECRET'),'deadlock-http-'.bin2hex(random_bytes(5)),(string)getenv('CM_MYSQL_PROVIDER_PAYMENT_ID_PAID'));}catch(Throwable $e){$timeoutControl->exec('SET GLOBAL innodb_lock_wait_timeout=50');throw $e;}$timeoutControl->exec('SET GLOBAL innodb_lock_wait_timeout=50');$a->rollBack();dmAssert(is_array($http)&&$http['error']===''&&$http['status']!==500,'webhook returned HTTP 500 under pessimistic lock contention');$notification='deadlock-redelivery-'.bin2hex(random_bytes(5));$first=webhook((string)getenv('CM_WEBHOOK_URL'),(string)getenv('CM_WEBHOOK_SECRET'),$notification,(string)getenv('CM_MYSQL_PROVIDER_PAYMENT_ID_PAID'));dmAssert($first['status']===200,'first webhook delivery failed: '.$first['status']);$afterFirst=snapshot($pdo,$paymentId,$orderId);$second=webhook((string)getenv('CM_WEBHOOK_URL'),(string)getenv('CM_WEBHOOK_SECRET'),$notification,(string)getenv('CM_MYSQL_PROVIDER_PAYMENT_ID_PAID));dmAssert($second['status']===200,'redelivery failed: '.$second['status']);$afterReplay=snapshot($pdo,$paymentId,$orderId);dmSame($afterFirst['history'],$afterReplay['history'],'redelivery duplicated order history');dmSame($afterFirst['stock'],$afterReplay['stock'],'redelivery duplicated stock movement');dmSame($afterFirst['audit'],$afterReplay['audit'],'redelivery duplicated audit');echo 'HTTP_LOCK_CONTENTION_STATUS: '.$http['status'].PHP_EOL;echo 'REDELIVERY_FIRST_STATUS: '.$first['status'].PHP_EOL;echo 'REDELIVERY_SECOND_STATUS: '.$second['status'].PHP_EOL;echo 'PERFORMANCE_SCHEMA_LOCKS: '.count($telemetryBeforeCross['locks']).PHP_EOL;echo 'PERFORMANCE_SCHEMA_WAITS: '.count($telemetryBeforeCross['waits']).PHP_EOL;echo "PASS: webhook_mysql_deadlock_test\n";
}catch(Throwable $e){fwrite(STDERR,'FAIL: '.$e->getMessage().PHP_EOL);exit(1);}